In [36]:
import numpy as np
import cv2

image = cv2.imread('./faces.jpg')

# Applying viola jones math which is in xml file to the image:

model = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')


cordinates , no_of_faces = model.detectMultiScale2(image)
print(cordinates)
print(len(cordinates))
if len(cordinates)>0:
    for i in range(len(cordinates)):
        sol = cordinates[i]
        pt1 = (sol[0],sol[1])
        pt2 = (sol[0]+sol[2], sol[1]+sol[3])
        cv2.rectangle(image, pt1, pt2, (0,0,255))
        font = cv2.FONT_HERSHEY_COMPLEX
        cv2.putText(image, str(i+1), (sol[0]+10,sol[1]-5), font, 0.5, (0,0,255), 1)

    text = 'Number of faces are = ' + str(len(cordinates))
    
else:
    text = 'no faces detected'
    
font = cv2.FONT_HERSHEY_COMPLEX
cv2.putText(image , text , (10 , 40) , font ,.5,(0,0,255) , 1)
cv2.imshow('image', image)
cv2.waitKey()
cv2.destroyAllWindows()

[[321  84 385 385]
 [894 573  52  52]
 [697 107 248 248]
 [ 88  75 316 316]]
4
